### ISSUE TITLE
add mechanism to flag bad data

### ISSUE THREAD

**Issue by hutershvili** [digiwhist/opentender-frontend#2]
Hi, 
OpenTender looks great. I spotted a case of bad data: he final price of a tender award is listed as 440.7 million, the award price – which appears to be correct – is 4.4 million, https://opentender.eu/at/tender/7411d1df-9b96-4649-9752-9220dc9a201a

Maybe you could consider to add a button for users to flag potential cases of bad data, so that somebody could manually go and check, and if necessary correct that data point – and/or to highlight on the page that data for a specific tender has been flagged as possibly incorrect.

**Comment by ffalt** [comment]
Hi, thank you! This is a very understandable feature request, but not a technical issue, rather an question for the digiwhist project, which discussed this. Currently we don't have someone to handle and verify reports like that. I'm not in the loop for this topic, but if my information is correct, funding is searched to offer something like that. 

As for the spotted conflicting data, it's in the source
http://ted.europa.eu/udl?uri=TED:NOTICE:420079-2013:TEXT:EN:HTML
While I agree 4,4 Million appears to be correct, further examination would be needed.
